proiect/aplicatie1/urls.py
# aici vor aparea roots pentru modulul de location denumit aplicatie1

# numele folosit ca referinta in redirecturile pe care le vom avea
from django.urls import path

from aplicatie1 import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationsView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adauga'),
    path('<int:pk>/update/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/stergere/', views.delete_location, name='sterge'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
    path('', views.CompaniesView.as_view(), name='lista_companii'),
    path('adaugare/', views.CreateCompaniesView.as_view(), name='adauga'),
    #pentru ca modifica o data deja existenta, folosim un primarykey
    path('<int:pk>/update/', views.UpdateCompaniesView.as_view(), name='modifica'),
    path('<int:pk>/delete/', views.delete_companie, name='sterge'),
    path('<int:pk>/activate/', views.activate_companie, name='activeaza'),
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    # url-ul pentru aplicatie1
    path('locations/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('profile/', include('user_profile.urls')),
]

proiect/user_profile/urls.py
from django.urls import path

from user_profile import views

app_name = 'userprofile'

urlpatterns = [
    path('start_timesheet/', views.new_timesheet, name='start_pontaj'),
    path('stop_timesheet/', views.stop_timesheet, name='stop_pontaj'),
]

proiect/aplicatie1/models.py
from django.db import models

# Create your models here.
class Locations(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=150)
    active = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.city} - {self.country}"

proiect/aplicatie2/models.py
from django.db import models

tipuri_companie = (('SRL', 'S.R.L'), ('SC', 'S.C'), ('SA', 'S.A'))



class Companies(models.Model):
    nume = models.CharField(max_length=100)
    website = models.CharField(max_length=50)
    tip_companie = models.CharField(max_length=10, choices=tipuri_companie)
    activ = models.BooleanField(default=1)

    def __str__(self):
        return f"{self.nume} - {self.tip_companie}"

proiect/user_profile/models.py
from django.db import models


class Logs(models.Model):

    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    action = models.CharField(max_length=10)
    url = models.CharField(max_length=100)


class Pontaj(models.Model):

    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(null=True)

proiect/aplicatie1/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie1.models import Locations


class LocationsView(LoginRequiredMixin, ListView):
    model = Locations
    template_name = 'aplicatie1/locations_index.html'


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Locations
    fields = ['city', 'country']
    template_name = 'aplicatie1/locations_form.html'

    def get_success_url(self):
        return reverse('locations:lista_locatii')

@login_required
def delete_location(request, pk):
    Locations.objects.filter(id=pk).update(active=0)
    return redirect('locations:lista_locatii')

@login_required
def activate_location(request, pk):
    Locations.objects.filter(id=pk).update(active=1)
    return redirect('locations:lista_locatii')

proiect/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie2.models import Companies


class CompaniesView(LoginRequiredMixin, ListView):
    model = Companies
    template_name = 'aplicatie2/companies_index.html'


class CreateCompaniesView(LoginRequiredMixin, CreateView):
    model = Companies
    fields = ['nume', 'website', 'tip_companie']
    template_name = 'aplicatie2/companies_form.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


class UpdateCompaniesView(LoginRequiredMixin, UpdateView):
    model = Companies
    fields = ['nume', 'website', 'tip_companie']
    template_name = 'aplicatie2/companies_form.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


@login_required
def delete_companie(request, pk):
    Companies.objects.filter(id=pk).update(activ=0)
    return redirect('companies:lista_companii')\

@login_required
def activate_companie(request, pk):
    Companies.objects.filter(id=pk).update(activ=1)
    return redirect('companies:lista_companii')

proiect/user_profile/views.py
import datetime

from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect

from user_profile.models import Pontaj


@login_required
def new_timesheet(request):
    Pontaj.objects.create(user_id=request.user.id, start_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def stop_timesheet(request):
    Pontaj.objects.filter(user_id=request.user.id, end_date=None).update(end_date=datetime.datetime.now())
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

proiect/templates/aplicatie1/locations_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{field.label}} {{field}} <br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

proiect/templates/aplicatie1/locations_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'locations:adauga' %}" class="btn btn-success">Adaugare locatie</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>City</th>
                <th>Country</th>
                <th>State</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in locations_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.city }}</td>
                    <td>{{ item.country }}</td>
                    <td>
                        {% if item.active == 1 %}
                        <span>Activ</span>
                        {% else %}
                        <span>Inactiv</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'locations:modifica' item.id %}" class="btn btn-success">Modifica</a>
                        {% if item.active == 1 %}
                        <a href="{% url 'locations:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                        {% else %}
                        <a href="{% url 'locations:activeaza' item.id %}" class="btn btn-info">Activeaza</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

proiect/templates/aplicatie2/companies_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{field.label}} {{field}} <br>
        {% endfor %}
        <button type="submit">Salveaza</button>
    </form>
{% endblock %}

proiect/templates/aplicatie2/companies_index.html
{% extends 'base.html' %}
{% block content %}
    <a href="{% url 'companies:adauga' %}" class="btn btn-success">Adaugare</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>Nume</th>
                <th>Website</th>
                <th>Tip</th>
                <th>Stare</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for item in companies_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ item.nume }}</td>
                <td>{{ item.website }}</td>
                <td>{{ item.tip_companie }}</td>
                <td>{% if item.activ == 1 %}
                    <span>Activ</span>
                {% else %}
                    <span>Inactiv</span>
                {% endif %}
                </td>
                <td>
                    <a href="{% url 'companies:modifica' item.id %}" class="btn btn-info">Modifica</a>
                    {% if item.activ == 1 %}
                    <a href="{% url 'companies:sterge' item.id %}" class="btn btn-danger">Sterge</a>
                    {% else %}
                    <a href="{% url 'companies:activeaza' item.id %}" class="btn btn-success">Activeaza</a>
                    {% endif%}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

proiect/templates/base.html
<html>
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>
                <a class="btn" href="/admin">Admin</a>
                {% if request.user.is_authenticated %}
                    <a class="btn" href="{% url 'locations:lista_locatii' %}">Locatii</a>
                    <a class="btn" href="{% url 'companies:lista_companii' %}">Companii</a>
                    <a class="btn" href="{% url 'logout' %}">Logout</a>
                    <span>Hi, {{ request.user.username|upper }}</span>
                    {% if ready_to_work is False %}
                        <a href="{% url 'userprofile:stop_pontaj' %}" class="btn btn-danger">Oprire Pontaj</a>
                    {% else %}
                        <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Start Pontaj</a>
                    {% endif %}
                {% endif %}
            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>